name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/ci-cd-setup
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install backend dependencies
        run: |
          pip install fastapi uvicorn pydantic
      - name: Run backend tests
        run: |
          pytest tests/
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run frontend tests
        run: |
          cd frontend && npm ci && npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Backend
        run: |
          echo "Deploying backend to server..."
      - name: Deploy Frontend
        run: |
          echo "Deploying frontend to server..."
